package main

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
)

func GenerateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + ".http.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-gohttp. DO NOT EDIT.")
	g.P(fmt.Sprintf("// source: %s.proto", file.GeneratedFilenamePrefix))
	g.P()
	g.P(fmt.Sprintf("package %s", file.GoPackageName))

	return g
}
