// Code generated by protoc-gen-go. DO NOT EDIT.
// source: all_pattern.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AllPatternMessage struct {
	Double               float64   `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
	Float                float32   `protobuf:"fixed32,2,opt,name=float,proto3" json:"float,omitempty"`
	Int32                int32     `protobuf:"varint,3,opt,name=int32,proto3" json:"int32,omitempty"`
	Int64                int64     `protobuf:"varint,4,opt,name=int64,proto3" json:"int64,omitempty"`
	Uint32               uint32    `protobuf:"varint,5,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Uint64               uint64    `protobuf:"varint,6,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Fixed32              uint32    `protobuf:"fixed32,7,opt,name=fixed32,proto3" json:"fixed32,omitempty"`
	Fixed64              uint64    `protobuf:"fixed64,8,opt,name=fixed64,proto3" json:"fixed64,omitempty"`
	Sfixed32             int32     `protobuf:"fixed32,9,opt,name=sfixed32,proto3" json:"sfixed32,omitempty"`
	Sfixed64             int64     `protobuf:"fixed64,10,opt,name=sfixed64,proto3" json:"sfixed64,omitempty"`
	Bool                 bool      `protobuf:"varint,11,opt,name=bool,proto3" json:"bool,omitempty"`
	String_              string    `protobuf:"bytes,12,opt,name=string,proto3" json:"string,omitempty"`
	Bytes                []byte    `protobuf:"bytes,14,opt,name=bytes,proto3" json:"bytes,omitempty"`
	RepeatedDouble       []float64 `protobuf:"fixed64,15,rep,packed,name=repeated_double,json=repeatedDouble,proto3" json:"repeated_double,omitempty"`
	RepeatedFloat        []float32 `protobuf:"fixed32,16,rep,packed,name=repeated_float,json=repeatedFloat,proto3" json:"repeated_float,omitempty"`
	RepeatedInt32        []int32   `protobuf:"varint,17,rep,packed,name=repeated_int32,json=repeatedInt32,proto3" json:"repeated_int32,omitempty"`
	RepeatedInt64        []int64   `protobuf:"varint,18,rep,packed,name=repeated_int64,json=repeatedInt64,proto3" json:"repeated_int64,omitempty"`
	RepeatedUint32       []uint32  `protobuf:"varint,19,rep,packed,name=repeated_uint32,json=repeatedUint32,proto3" json:"repeated_uint32,omitempty"`
	RepeatedUint64       []uint64  `protobuf:"varint,20,rep,packed,name=repeated_uint64,json=repeatedUint64,proto3" json:"repeated_uint64,omitempty"`
	RepeatedFixed32      []uint32  `protobuf:"fixed32,21,rep,packed,name=repeated_fixed32,json=repeatedFixed32,proto3" json:"repeated_fixed32,omitempty"`
	RepeatedFixed64      []uint64  `protobuf:"fixed64,22,rep,packed,name=repeated_fixed64,json=repeatedFixed64,proto3" json:"repeated_fixed64,omitempty"`
	RepeatedSfixed32     []int32   `protobuf:"fixed32,23,rep,packed,name=repeated_sfixed32,json=repeatedSfixed32,proto3" json:"repeated_sfixed32,omitempty"`
	RepeatedSfixed64     []int64   `protobuf:"fixed64,24,rep,packed,name=repeated_sfixed64,json=repeatedSfixed64,proto3" json:"repeated_sfixed64,omitempty"`
	RepeatedBool         []bool    `protobuf:"varint,25,rep,packed,name=repeated_bool,json=repeatedBool,proto3" json:"repeated_bool,omitempty"`
	RepeatedString       []string  `protobuf:"bytes,26,rep,name=repeated_string,json=repeatedString,proto3" json:"repeated_string,omitempty"`
	RepeatedBytes        [][]byte  `protobuf:"bytes,28,rep,name=repeated_bytes,json=repeatedBytes,proto3" json:"repeated_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AllPatternMessage) Reset()         { *m = AllPatternMessage{} }
func (m *AllPatternMessage) String() string { return proto.CompactTextString(m) }
func (*AllPatternMessage) ProtoMessage()    {}
func (*AllPatternMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_de8ae7e6b985e167, []int{0}
}

func (m *AllPatternMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllPatternMessage.Unmarshal(m, b)
}
func (m *AllPatternMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllPatternMessage.Marshal(b, m, deterministic)
}
func (m *AllPatternMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllPatternMessage.Merge(m, src)
}
func (m *AllPatternMessage) XXX_Size() int {
	return xxx_messageInfo_AllPatternMessage.Size(m)
}
func (m *AllPatternMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AllPatternMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AllPatternMessage proto.InternalMessageInfo

func (m *AllPatternMessage) GetDouble() float64 {
	if m != nil {
		return m.Double
	}
	return 0
}

func (m *AllPatternMessage) GetFloat() float32 {
	if m != nil {
		return m.Float
	}
	return 0
}

func (m *AllPatternMessage) GetInt32() int32 {
	if m != nil {
		return m.Int32
	}
	return 0
}

func (m *AllPatternMessage) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func (m *AllPatternMessage) GetUint32() uint32 {
	if m != nil {
		return m.Uint32
	}
	return 0
}

func (m *AllPatternMessage) GetUint64() uint64 {
	if m != nil {
		return m.Uint64
	}
	return 0
}

func (m *AllPatternMessage) GetFixed32() uint32 {
	if m != nil {
		return m.Fixed32
	}
	return 0
}

func (m *AllPatternMessage) GetFixed64() uint64 {
	if m != nil {
		return m.Fixed64
	}
	return 0
}

func (m *AllPatternMessage) GetSfixed32() int32 {
	if m != nil {
		return m.Sfixed32
	}
	return 0
}

func (m *AllPatternMessage) GetSfixed64() int64 {
	if m != nil {
		return m.Sfixed64
	}
	return 0
}

func (m *AllPatternMessage) GetBool() bool {
	if m != nil {
		return m.Bool
	}
	return false
}

func (m *AllPatternMessage) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *AllPatternMessage) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedDouble() []float64 {
	if m != nil {
		return m.RepeatedDouble
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedFloat() []float32 {
	if m != nil {
		return m.RepeatedFloat
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedInt32() []int32 {
	if m != nil {
		return m.RepeatedInt32
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedInt64() []int64 {
	if m != nil {
		return m.RepeatedInt64
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedUint32() []uint32 {
	if m != nil {
		return m.RepeatedUint32
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedUint64() []uint64 {
	if m != nil {
		return m.RepeatedUint64
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedFixed32() []uint32 {
	if m != nil {
		return m.RepeatedFixed32
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedFixed64() []uint64 {
	if m != nil {
		return m.RepeatedFixed64
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedSfixed32() []int32 {
	if m != nil {
		return m.RepeatedSfixed32
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedSfixed64() []int64 {
	if m != nil {
		return m.RepeatedSfixed64
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedBool() []bool {
	if m != nil {
		return m.RepeatedBool
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedString() []string {
	if m != nil {
		return m.RepeatedString
	}
	return nil
}

func (m *AllPatternMessage) GetRepeatedBytes() [][]byte {
	if m != nil {
		return m.RepeatedBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*AllPatternMessage)(nil), "main.AllPatternMessage")
}

func init() { proto.RegisterFile("all_pattern.proto", fileDescriptor_de8ae7e6b985e167) }

var fileDescriptor_de8ae7e6b985e167 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcd, 0x8a, 0xdb, 0x30,
	0x14, 0x85, 0x51, 0x94, 0x38, 0x89, 0x9a, 0x5f, 0x35, 0x9d, 0x51, 0xc3, 0x2c, 0x2e, 0x53, 0x4a,
	0x6f, 0x29, 0x24, 0x90, 0x08, 0xed, 0x1b, 0xca, 0x40, 0x17, 0x85, 0xa2, 0x69, 0x37, 0xdd, 0x04,
	0x87, 0x78, 0x82, 0xc1, 0xb5, 0x42, 0xac, 0x81, 0x76, 0xdb, 0x57, 0xe8, 0xa3, 0xf5, 0x05, 0xba,
	0xe8, 0x83, 0x14, 0x5b, 0xb2, 0x9d, 0x1f, 0x66, 0xe7, 0x73, 0xf4, 0x59, 0x48, 0xe7, 0xe8, 0xb2,
	0x71, 0x98, 0x24, 0xeb, 0x7d, 0x68, 0x6d, 0x74, 0x48, 0x67, 0xfb, 0x83, 0xb1, 0x86, 0x37, 0xbf,
	0x87, 0x71, 0x3a, 0xbd, 0xd9, 0x19, 0xb3, 0x4b, 0xa2, 0x79, 0xb8, 0x8f, 0xe7, 0x61, 0x9a, 0x1a,
	0x1b, 0xda, 0xd8, 0xa4, 0x99, 0x63, 0x6e, 0xff, 0x06, 0x6c, 0xfc, 0x3e, 0x49, 0x3e, 0xbb, 0x1f,
	0x3f, 0x45, 0x59, 0x16, 0xee, 0x22, 0x7e, 0xc5, 0x82, 0xad, 0x79, 0xdc, 0x24, 0x91, 0x20, 0x40,
	0x90, 0x68, 0xaf, 0xf8, 0x84, 0xb5, 0x1e, 0x12, 0x13, 0x5a, 0xd1, 0x00, 0x82, 0x0d, 0xed, 0x44,
	0xee, 0xc6, 0xa9, 0x5d, 0x2e, 0x04, 0x05, 0x82, 0x2d, 0xed, 0x84, 0x77, 0x95, 0x14, 0x4d, 0x20,
	0x48, 0xb5, 0x13, 0xf9, 0xce, 0x8f, 0x0e, 0x6e, 0x01, 0xc1, 0xbe, 0xf6, 0xaa, 0xf4, 0x95, 0x14,
	0x01, 0x10, 0x6c, 0x6a, 0xaf, 0xb8, 0x60, 0xed, 0x87, 0xf8, 0x47, 0xb4, 0x5d, 0x2e, 0x44, 0x1b,
	0x08, 0xb6, 0x75, 0x29, 0xab, 0x15, 0x25, 0x45, 0x07, 0x08, 0x06, 0xba, 0x94, 0x7c, 0xca, 0x3a,
	0x59, 0xf9, 0x53, 0x17, 0x08, 0x0e, 0x75, 0xa5, 0xeb, 0x35, 0x25, 0x05, 0x03, 0x82, 0x23, 0x5d,
	0x69, 0xce, 0x59, 0x73, 0x63, 0x4c, 0x22, 0x9e, 0x01, 0xc1, 0x8e, 0x2e, 0xbe, 0xf3, 0x73, 0x65,
	0xf6, 0x10, 0xa7, 0x3b, 0xd1, 0x03, 0x82, 0x5d, 0xed, 0x55, 0x7e, 0xbb, 0xcd, 0x4f, 0x1b, 0x65,
	0x62, 0x00, 0x04, 0x7b, 0xda, 0x09, 0xfe, 0x86, 0x0d, 0x0f, 0xd1, 0x3e, 0x0a, 0x6d, 0xb4, 0x5d,
	0xfb, 0x00, 0x87, 0x40, 0x91, 0xe8, 0x41, 0x69, 0x7f, 0x70, 0x41, 0xbe, 0x66, 0x95, 0xb3, 0x76,
	0x89, 0x8e, 0x80, 0x62, 0x43, 0xf7, 0x4b, 0xf7, 0xae, 0x48, 0xf6, 0x18, 0x73, 0xa9, 0x8d, 0x81,
	0x62, 0xab, 0xc6, 0x3e, 0x16, 0xe1, 0x9d, 0x61, 0x4a, 0x0a, 0x0e, 0x14, 0xe9, 0x09, 0xa6, 0xe4,
	0xc9, 0xe9, 0x7c, 0x09, 0xcf, 0x81, 0x62, 0xbf, 0x3e, 0xdd, 0x57, 0x57, 0xc6, 0x39, 0xa8, 0xa4,
	0x98, 0x00, 0xc5, 0xe6, 0x29, 0xa8, 0x24, 0x7f, 0xcb, 0x46, 0xf5, 0x35, 0x7c, 0xe2, 0x2f, 0x80,
	0x62, 0x5b, 0x57, 0x1b, 0xdc, 0xf9, 0xe0, 0x2f, 0x50, 0x25, 0xc5, 0x15, 0x50, 0x0c, 0xce, 0x50,
	0x25, 0xf9, 0x3b, 0x36, 0xae, 0xd0, 0xaa, 0xc8, 0x6b, 0xa0, 0x38, 0xd4, 0xd5, 0x1e, 0xf7, 0x65,
	0xa1, 0x97, 0xb0, 0x92, 0x42, 0x00, 0xc5, 0xd1, 0x39, 0xac, 0x24, 0x7f, 0xc5, 0xaa, 0x48, 0xd6,
	0x45, 0xd5, 0x2f, 0x81, 0x62, 0x47, 0xf7, 0x4a, 0x73, 0x95, 0x57, 0x7e, 0x7c, 0x7b, 0xdf, 0xfd,
	0x14, 0x28, 0x76, 0xeb, 0xdb, 0xdf, 0xbb, 0x37, 0x70, 0x1c, 0xbb, 0x7b, 0x0c, 0x37, 0x40, 0xb1,
	0x57, 0xc7, 0xbe, 0xca, 0xcd, 0xc5, 0x86, 0xb1, 0x7a, 0xc2, 0xf8, 0x97, 0x13, 0x75, 0x3d, 0xcb,
	0x67, 0x74, 0x76, 0x31, 0x81, 0xd3, 0xa7, 0x16, 0x6e, 0x27, 0xbf, 0xfe, 0xfc, 0xfb, 0xdd, 0x18,
	0xf0, 0xde, 0x3c, 0x4c, 0x92, 0xb9, 0x1f, 0xf8, 0x55, 0xf0, 0xad, 0x18, 0xf6, 0x4d, 0x50, 0x4c,
	0xf5, 0xf2, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0xa6, 0x99, 0xa0, 0x0e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AllPatternClient is the client API for AllPattern service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AllPatternClient interface {
	AllPattern(ctx context.Context, in *AllPatternMessage, opts ...grpc.CallOption) (*AllPatternMessage, error)
}

type allPatternClient struct {
	cc *grpc.ClientConn
}

func NewAllPatternClient(cc *grpc.ClientConn) AllPatternClient {
	return &allPatternClient{cc}
}

func (c *allPatternClient) AllPattern(ctx context.Context, in *AllPatternMessage, opts ...grpc.CallOption) (*AllPatternMessage, error) {
	out := new(AllPatternMessage)
	err := c.cc.Invoke(ctx, "/main.AllPattern/AllPattern", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AllPatternServer is the server API for AllPattern service.
type AllPatternServer interface {
	AllPattern(context.Context, *AllPatternMessage) (*AllPatternMessage, error)
}

// UnimplementedAllPatternServer can be embedded to have forward compatible implementations.
type UnimplementedAllPatternServer struct {
}

func (*UnimplementedAllPatternServer) AllPattern(ctx context.Context, req *AllPatternMessage) (*AllPatternMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllPattern not implemented")
}

func RegisterAllPatternServer(s *grpc.Server, srv AllPatternServer) {
	s.RegisterService(&_AllPattern_serviceDesc, srv)
}

func _AllPattern_AllPattern_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllPatternMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AllPatternServer).AllPattern(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.AllPattern/AllPattern",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AllPatternServer).AllPattern(ctx, req.(*AllPatternMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _AllPattern_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.AllPattern",
	HandlerType: (*AllPatternServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllPattern",
			Handler:    _AllPattern_AllPattern_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "all_pattern.proto",
}
