// Code generated by protoc-gen-go. DO NOT EDIT.
// source: httprule.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetMessageRequest struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageRequest) Reset()         { *m = GetMessageRequest{} }
func (m *GetMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessageRequest) ProtoMessage()    {}
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d0d5480baba1876, []int{0}
}

func (m *GetMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageRequest.Unmarshal(m, b)
}
func (m *GetMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageRequest.Marshal(b, m, deterministic)
}
func (m *GetMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageRequest.Merge(m, src)
}
func (m *GetMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessageRequest.Size(m)
}
func (m *GetMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageRequest proto.InternalMessageInfo

func (m *GetMessageRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *GetMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetMessageRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type GetMessageResponse struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageResponse) Reset()         { *m = GetMessageResponse{} }
func (m *GetMessageResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessageResponse) ProtoMessage()    {}
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d0d5480baba1876, []int{1}
}

func (m *GetMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageResponse.Unmarshal(m, b)
}
func (m *GetMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageResponse.Marshal(b, m, deterministic)
}
func (m *GetMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageResponse.Merge(m, src)
}
func (m *GetMessageResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessageResponse.Size(m)
}
func (m *GetMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageResponse proto.InternalMessageInfo

func (m *GetMessageResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *GetMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetMessageResponse) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type SubMessage struct {
	Subfield             string   `protobuf:"bytes,1,opt,name=subfield,proto3" json:"subfield,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubMessage) Reset()         { *m = SubMessage{} }
func (m *SubMessage) String() string { return proto.CompactTextString(m) }
func (*SubMessage) ProtoMessage()    {}
func (*SubMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d0d5480baba1876, []int{2}
}

func (m *SubMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubMessage.Unmarshal(m, b)
}
func (m *SubMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubMessage.Marshal(b, m, deterministic)
}
func (m *SubMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubMessage.Merge(m, src)
}
func (m *SubMessage) XXX_Size() int {
	return xxx_messageInfo_SubMessage.Size(m)
}
func (m *SubMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SubMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SubMessage proto.InternalMessageInfo

func (m *SubMessage) GetSubfield() string {
	if m != nil {
		return m.Subfield
	}
	return ""
}

type UpdateMessageRequest struct {
	MessageId            string      `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Sub                  *SubMessage `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Message              string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateMessageRequest) Reset()         { *m = UpdateMessageRequest{} }
func (m *UpdateMessageRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMessageRequest) ProtoMessage()    {}
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d0d5480baba1876, []int{3}
}

func (m *UpdateMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMessageRequest.Unmarshal(m, b)
}
func (m *UpdateMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMessageRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMessageRequest.Merge(m, src)
}
func (m *UpdateMessageRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMessageRequest.Size(m)
}
func (m *UpdateMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMessageRequest proto.InternalMessageInfo

func (m *UpdateMessageRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *UpdateMessageRequest) GetSub() *SubMessage {
	if m != nil {
		return m.Sub
	}
	return nil
}

func (m *UpdateMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateMessageResponse struct {
	MessageId            string      `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Sub                  *SubMessage `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Message              string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateMessageResponse) Reset()         { *m = UpdateMessageResponse{} }
func (m *UpdateMessageResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMessageResponse) ProtoMessage()    {}
func (*UpdateMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d0d5480baba1876, []int{4}
}

func (m *UpdateMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMessageResponse.Unmarshal(m, b)
}
func (m *UpdateMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMessageResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMessageResponse.Merge(m, src)
}
func (m *UpdateMessageResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMessageResponse.Size(m)
}
func (m *UpdateMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMessageResponse proto.InternalMessageInfo

func (m *UpdateMessageResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *UpdateMessageResponse) GetSub() *SubMessage {
	if m != nil {
		return m.Sub
	}
	return nil
}

func (m *UpdateMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetMessageRequest)(nil), "helloworld.GetMessageRequest")
	proto.RegisterType((*GetMessageResponse)(nil), "helloworld.GetMessageResponse")
	proto.RegisterType((*SubMessage)(nil), "helloworld.SubMessage")
	proto.RegisterType((*UpdateMessageRequest)(nil), "helloworld.UpdateMessageRequest")
	proto.RegisterType((*UpdateMessageResponse)(nil), "helloworld.UpdateMessageResponse")
}

func init() { proto.RegisterFile("httprule.proto", fileDescriptor_9d0d5480baba1876) }

var fileDescriptor_9d0d5480baba1876 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x49, 0x53, 0xfa, 0xbe, 0x19, 0x51, 0x70, 0x50, 0x89, 0xd1, 0x4a, 0x9b, 0x53, 0x10,
	0x4c, 0xb0, 0xbd, 0x79, 0xf4, 0x22, 0x1e, 0xbc, 0x44, 0xbc, 0x78, 0xd1, 0x0d, 0x59, 0xd3, 0xc0,
	0x76, 0x37, 0x76, 0x77, 0x15, 0x2d, 0xbd, 0x78, 0x11, 0xcf, 0x7e, 0x34, 0xbf, 0x82, 0x1f, 0x44,
	0x4c, 0x52, 0x93, 0xaa, 0x15, 0x45, 0x6f, 0x3b, 0x3b, 0x0f, 0xf3, 0x7b, 0xe6, 0x0f, 0x2c, 0x0d,
	0x94, 0xca, 0x46, 0x9a, 0x51, 0x3f, 0x1b, 0x09, 0x25, 0x10, 0x06, 0x94, 0x31, 0x71, 0x2d, 0x46,
	0x2c, 0x76, 0x36, 0x13, 0x21, 0x12, 0x46, 0x03, 0x92, 0xa5, 0x01, 0xe1, 0x5c, 0x28, 0xa2, 0x52,
	0xc1, 0x65, 0xa1, 0x74, 0xcf, 0x61, 0xf9, 0x80, 0xaa, 0x23, 0x2a, 0x25, 0x49, 0x68, 0x48, 0x2f,
	0x35, 0x95, 0x0a, 0xdb, 0x00, 0xc3, 0xe2, 0xe7, 0x2c, 0x8d, 0x6d, 0xa3, 0x63, 0x78, 0x56, 0x68,
	0x95, 0x3f, 0x87, 0x31, 0xda, 0xf0, 0xaf, 0x0c, 0xec, 0x46, 0x9e, 0x9b, 0x86, 0x88, 0xd0, 0x54,
	0x24, 0x91, 0xb6, 0xd9, 0x31, 0x3d, 0x2b, 0xcc, 0xdf, 0x2e, 0x01, 0xac, 0x13, 0x64, 0x26, 0xb8,
	0xa4, 0xbf, 0x47, 0x34, 0x6b, 0x08, 0x0f, 0xe0, 0x58, 0x47, 0x25, 0x02, 0x1d, 0xf8, 0x2f, 0x75,
	0x74, 0x91, 0x52, 0x36, 0x2d, 0xfc, 0x16, 0xbb, 0x37, 0xb0, 0x72, 0x92, 0xc5, 0x44, 0xd1, 0x9f,
	0x75, 0xec, 0x81, 0x29, 0x75, 0x94, 0x5b, 0x59, 0xe8, 0xad, 0xf9, 0xd5, 0x74, 0xfd, 0x8a, 0x1b,
	0xbe, 0x4a, 0xea, 0xc6, 0xcd, 0x19, 0xe3, 0xee, 0x2d, 0xac, 0xbe, 0x43, 0x7f, 0x6f, 0x14, 0x7f,
	0xc0, 0xee, 0xdd, 0x37, 0xc0, 0x2a, 0xa4, 0x29, 0x4f, 0x90, 0x03, 0x54, 0x1b, 0xc1, 0x76, 0xbd,
	0xe4, 0x87, 0x5b, 0x70, 0xb6, 0xe6, 0xa5, 0x0b, 0xf7, 0x6e, 0xf7, 0xee, 0xe9, 0xf9, 0xb1, 0xb1,
	0x81, 0xeb, 0xc1, 0xd5, 0x6e, 0x50, 0xf2, 0x64, 0x30, 0xae, 0x3a, 0x9a, 0xe0, 0x83, 0x01, 0x8b,
	0x33, 0xad, 0x63, 0xa7, 0x5e, 0xf4, 0xb3, 0x85, 0x38, 0xdd, 0x2f, 0x14, 0x25, 0xb9, 0x9f, 0x93,
	0x77, 0x1c, 0x6f, 0x2e, 0x39, 0x18, 0x4b, 0x1d, 0xf9, 0xd3, 0xe5, 0x4f, 0xf6, 0x8c, 0xed, 0xfd,
	0xd6, 0x69, 0x73, 0x48, 0x52, 0x1e, 0xb5, 0xf2, 0xf3, 0xef, 0xbf, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x44, 0xae, 0x1c, 0x61, 0x3a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessagingClient is the client API for Messaging service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessagingClient interface {
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
	UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error)
}

type messagingClient struct {
	cc *grpc.ClientConn
}

func NewMessagingClient(cc *grpc.ClientConn) MessagingClient {
	return &messagingClient{cc}
}

func (c *messagingClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	out := new(GetMessageResponse)
	err := c.cc.Invoke(ctx, "/helloworld.Messaging/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*UpdateMessageResponse, error) {
	out := new(UpdateMessageResponse)
	err := c.cc.Invoke(ctx, "/helloworld.Messaging/UpdateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagingServer is the server API for Messaging service.
type MessagingServer interface {
	GetMessage(context.Context, *GetMessageRequest) (*GetMessageResponse, error)
	UpdateMessage(context.Context, *UpdateMessageRequest) (*UpdateMessageResponse, error)
}

// UnimplementedMessagingServer can be embedded to have forward compatible implementations.
type UnimplementedMessagingServer struct {
}

func (*UnimplementedMessagingServer) GetMessage(ctx context.Context, req *GetMessageRequest) (*GetMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (*UnimplementedMessagingServer) UpdateMessage(ctx context.Context, req *UpdateMessageRequest) (*UpdateMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMessage not implemented")
}

func RegisterMessagingServer(s *grpc.Server, srv MessagingServer) {
	s.RegisterService(&_Messaging_serviceDesc, srv)
}

func _Messaging_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Messaging/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_UpdateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).UpdateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Messaging/UpdateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).UpdateMessage(ctx, req.(*UpdateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Messaging_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Messaging",
	HandlerType: (*MessagingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessage",
			Handler:    _Messaging_GetMessage_Handler,
		},
		{
			MethodName: "UpdateMessage",
			Handler:    _Messaging_UpdateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "httprule.proto",
}
